# Generated by Django 4.0.3 on 2022-07-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_userprofile_profile_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
