# Generated by Django 4.0.3 on 2022-07-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_alter_userprofile_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_points',
            field=models.IntegerField(default=0),
        ),
    ]
