# Generated by Django 4.0.3 on 2022-07-06 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='climbedRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climbed_route_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=60, unique=True)),
                ('route_grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_gender', models.CharField(max_length=30)),
                ('profile_birth', models.DateField()),
                ('profile_active', models.BooleanField(default=True)),
                ('profile_is_staff', models.BooleanField(default=False)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_name', to=settings.AUTH_USER_MODEL)),
                ('profile_routes', models.ManyToManyField(default=None, related_name='profile_routes', to='ClimbingApp.climbedroute')),
            ],
        ),
        migrations.AddField(
            model_name='climbedroute',
            name='climbed_route_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbed_route_name', to='ClimbingApp.route'),
        ),
    ]
