# Generated by Django 4.0.3 on 2022-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingApp', '0004_alter_userprofile_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_gender',
            field=models.CharField(max_length=7),
        ),
    ]
